<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="om-PC" ignored="0" name="Test" tests="8" failures="1" timestamp="2019-11-07T10:13:30 IST" time="0.229" errors="0">
  <testcase name="test6" time="0.01" classname="testNGPart1.testNGAnnotation"/>
  <testcase name="test1" time="0.018" classname="testNGPart1.testNGAnnotation">
    <failure type="java.lang.AssertionError" message="expected [test2] but found [test1]">
      <![CDATA[java.lang.AssertionError: expected [test2] but found [test1]
at testNGPart1.testNGAnnotation.test1(testNGAnnotation.java:41)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
  <testcase name="test3" time="0.0" classname="testNGPart1.testNGAnnotation">
    <skipped/>
  </testcase> <!-- test3 -->
  <testcase name="test2" time="0.002" classname="testNGPart1.testNGAnnotation"/>
  <testcase name="test4" time="0.002" classname="testNGPart1.testNGAnnotation"/>
  <testcase name="test4" time="0.007" classname="testNGPart1.testNGAnnotation"/>
  <testcase name="test4" time="0.002" classname="testNGPart1.testNGAnnotation"/>
  <testcase name="test5" time="0.026" classname="testNGPart1.testNGAnnotation"/>
</testsuite> <!-- Test -->
